export type menuType = {
    id: number,
    name: string,
    translate?: string,
    pathnext: string,
    pathexpo?: string,
    icon: string,
    icontype: string,
    open?: boolean,
    label?: Object,
    submenu?: menuType[]
  }
  

export const Menu: menuType[] = [
    {
        id: 20,
        name: 'Business',
        icon: 'angle-up',
        translate: 'sidebar.nav.Legal',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/business',
        pathexpo: 'business/index',
    },
    {
        id: 19,
        name: 'Restaurant',
        icon: 'angle-up',
        translate: 'sidebar.nav.Restaurant',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/restaurants',
        pathexpo: 'restaurants/index',
    },
    {
        id: 3,
        name: 'Chat',
        icon: 'comments',
        translate: 'sidebar.nav.Chat',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/chat',
        pathexpo: 'chat/index',
    },
    {
        id: 4,
        name: 'Diagnostics',
        icon: 'share-square',
        translate: 'sidebar.nav.Diagnostics',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/diagnostics',
    },
    {
        id: 5,
        name: 'Learning',
        icon: 'angellist',
        translate: 'sidebar.nav.Learning',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/learning',
    },
    {
        id: 6,
        name: 'Teaching',
        icon: 'desktop',
        translate: 'sidebar.nav.Teaching',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/teaching',
    },
    {
        id: 7,
        name: 'Testing',
        icon: 'paper-plane',
        translate: 'sidebar.nav.Testing',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/testing',
    },
    {
        id: 11,
        name: 'News',
        icon: 'file',
        translate: 'sidebar.nav.News',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/news',
        pathexpo: 'news/index',
    },
    {
        id: 14,
        name: 'About',
        icon: 'map',
        translate: 'sidebar.nav.About',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/about',
        pathexpo: 'about/index',
    },
    {
        id: 15,
        name: 'Help',
        icon: 'question',
        translate: 'sidebar.nav.Chat',
        icontype: 'FontAwesome5',
        open: true,
        pathnext: '/help',
        pathexpo: 'help',
    },


];


