FROM node:18

RUN yarn global add @strapi/strapi

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

WORKDIR /srv/app
COPY ./package.json .
COPY ./yarn.lock .
# COPY ./patches ./patches
RUN ls & yarn

COPY . .
RUN yarn build

EXPOSE 1337
# CMD ["strapi", "configuration:restore", "-f", "dump.json", "&&", "strapi", "develop"]
# CMD ["strapi", "develop"]
CMD ["sh","-c","yarn restore && yarn start"]
# CMD ["sh","-c","yarn start"]

