kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-operator-fastmdm-#{Build.SourceBranchName}#
subjects:
  - kind: ServiceAccount
    name: postgres-operator
    namespace: fastmdm-#{Build.SourceBranchName}#
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-operator
