FROM node:18

RUN yarn global add next

WORKDIR /usr/src/app
COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install --network-timeout 1000000

COPY . .
RUN yarn build

EXPOSE 3002
CMD [ "yarn", "web"]
