apiVersion: v1
kind: Service
metadata:
  name: postgres-operator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: postgres-operator
---
kind: Service
apiVersion: v1
metadata:
  name: acid-postgres-cluster-external
  labels:
    application: spilo
    cluster-name: acid-postgres-cluster
    spilo-role: master
    team: acid
spec:
  selector:
    application: spilo
    cluster-name: acid-postgres-cluster
    spilo-role: master
    team: acid
  ports:
    - name: postgresql
      protocol: TCP
      port: #{database-port-external}#
      targetPort: 5432
  type: ClusterIP
  externalIPs:
    - #{database-host-external}#


