apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-fastmdm-prod-zalando-0-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-fastmdm-prod-zalando-0-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-fastmdm-prod-zalando-0-sc
  local:
    path: /mnt/ssd200gb/fastmdm-prod-zalando-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kuber2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-fastmdm-prod-zalando-1-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-fastmdm-prod-zalando-1-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-fastmdm-prod-zalando-1-sc
  local:
    path: /mnt/ssd200gb/fastmdm-prod-zalando-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kuber3
