/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import calendar from "@offset-dev/strapi-calendar/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import multiTenant from "strapi-plugin-multi-tenant/strapi-admin";
import translate from "strapi-plugin-translate/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    calendar: calendar,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "multi-tenant": multiTenant,
    translate: translate,
  },
});
